apiVersion: v2
description: Web frontend for FTF cattle housing scheme
name: ffc-grants-cattle-housing-web
# this version is automatically updated in the build pipline
version: 1.0.0
dependencies:
  - name: ffc-helm-library
    version: ^4.0.0
    repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
